#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] ; then
  echo "Script Requires More Parameters"
  exit 0  
elif [ -n "$3" ] ; then
  echo "To Many Parameters"
  exit 0
else
  for i in *$1 
  do
    mv "$i" "$(basename "$i" "$1")"$2"" 
  done
  exit 0
fi

